[build]
  command = "npm run build"
  publish = "dist/di-learn/browser"

# Angular SPA routing uchun — barcha yo'llar index.html ga yo'naltiriladi
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
